### ISSUE TITLE
Web Doctor need changes for the rsbuild doctor.

### ISSUE THREAD

**Issue by easy1090** [web-infra-dev/rsbuild#336]
```[tasklist]
### Tasks
- [ ] https://github.com/web-infra-dev/rsbuild/issues/338
- [ ] https://github.com/web-infra-dev/rsbuild/issues/337
- [ ] https://github.com/web-infra-dev/rsbuild/issues/463
```
